use crate::components::StateType;
use crate::systems::collision::HitEvent;

/// Strength of a hit, used to select the appropriate sound effect.
/// Mirrors tickle_audio::HitStrength but lives in core to avoid circular deps.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HitSoundStrength {
    Light,
    Medium,
    Heavy,
}

impl HitSoundStrength {
    pub fn from_damage(damage: i32) -> Self {
        if damage >= 1500 {
            HitSoundStrength::Heavy
        } else if damage >= 800 {
            HitSoundStrength::Medium
        } else {
            HitSoundStrength::Light
        }
    }
}

/// Audio events generated by game systems, to be consumed by the audio layer.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GameAudioEvent {
    HitSound { strength: HitSoundStrength },
    StateChangeSound { new_state: StateType },
    RoundStart,
    RoundEnd,
}

/// Generate audio events from hit events produced by the collision system.
pub fn audio_events_from_hits(hit_events: &[HitEvent]) -> Vec<GameAudioEvent> {
    hit_events
        .iter()
        .map(|hit| GameAudioEvent::HitSound {
            strength: HitSoundStrength::from_damage(hit.hitbox.damage),
        })
        .collect()
}

/// Generate an audio event when a fighter changes state.
pub fn audio_event_from_state_change(new_state: StateType) -> Option<GameAudioEvent> {
    // Only certain state transitions produce sounds
    match new_state {
        StateType::Hitstun | StateType::Blockstun => {
            Some(GameAudioEvent::StateChangeSound { new_state })
        }
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::components::Hitbox;
    use crate::math::{LogicRect, LogicVec2};

    fn make_hit(damage: i32) -> HitEvent {
        HitEvent {
            attacker: 0,
            defender: 1,
            hitbox: Hitbox {
                rect: LogicRect::new(0, 0, 100, 100),
                damage,
                hitstun: 10,
                blockstun: 5,
                knockback: LogicVec2::new(0, 0),
                hit_type: crate::components::HitType::Mid,
            },
        }
    }

    #[test]
    fn test_hit_sound_strength_from_damage() {
        assert_eq!(HitSoundStrength::from_damage(100), HitSoundStrength::Light);
        assert_eq!(HitSoundStrength::from_damage(800), HitSoundStrength::Medium);
        assert_eq!(HitSoundStrength::from_damage(2000), HitSoundStrength::Heavy);
    }

    #[test]
    fn test_audio_events_from_hits() {
        let hits = vec![make_hit(500), make_hit(1000), make_hit(2000)];
        let events = audio_events_from_hits(&hits);
        assert_eq!(events.len(), 3);
        assert_eq!(
            events[0],
            GameAudioEvent::HitSound {
                strength: HitSoundStrength::Light
            }
        );
        assert_eq!(
            events[1],
            GameAudioEvent::HitSound {
                strength: HitSoundStrength::Medium
            }
        );
        assert_eq!(
            events[2],
            GameAudioEvent::HitSound {
                strength: HitSoundStrength::Heavy
            }
        );
    }

    #[test]
    fn test_audio_event_from_state_change() {
        assert!(audio_event_from_state_change(StateType::Hitstun).is_some());
        assert!(audio_event_from_state_change(StateType::Blockstun).is_some());
        assert!(audio_event_from_state_change(StateType::Idle).is_none());
        assert!(audio_event_from_state_change(StateType::Jump).is_none());
    }

    #[test]
    fn test_empty_hits_produce_no_events() {
        let events = audio_events_from_hits(&[]);
        assert!(events.is_empty());
    }
}
